---
- name: "Configure Ethernet Network Group Policy for Mgmt Cohesity Data Access ( same VLAN) "
  vars:
    api_info: &api_info_mgmt
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  cisco.intersight.intersight_rest_api:
    <<: *api_info_mgmt
    resource_path: /fabric/EthNetworkGroupPolicies
    query_params:
       $filter: "Name eq '{{ name_of_network_group_policy_for_management }}'"
    api_body: {
      "Name": "{{ name_of_network_group_policy_for_management }}",
      "Description": "{{ description_of_network_group_policy_for_management }}",

      "Organization": {
         "Moid": "{{ intersight_org.api_response.Moid }}"
       },

      "VlanSettings": {
         "NativeVlan": "{{ native_vlan_for_mgmt_vnic }}",
         "AllowedVlans": "{{ allowed_vlans_for_mgmt_vnic }}"
         }
      }
  register: management_network_group_policy

