---

- name: "Configure LAN Connectivity Policy"
  vars:
    api_info: &api_info_lan_conn
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"
  block:
  - name: "LAN Connectivity Policy for Cohesity"
    cisco.intersight.intersight_rest_api:
          <<: *api_info_lan_conn
          resource_path: /vnic/LanConnectivityPolicies
          query_params:
             $filter: "Name eq '{{ name_of_lan_connectivity_policy }}'"
          api_body: {
              "Name": "{{ name_of_lan_connectivity_policy }}",
              "Description": "{{ description_of_lan_connectivity_policy }}",

              "TargetPlatform": "FIAttached",
              "AzureQosEnabled": false,
              "IqnAllocationType": "None",
              "PlacementMode": "custom",
              "IqnPool": "",
              "StaticIqnName": "",

              "Organization": {
                 "Moid": "{{ intersight_org.api_response.Moid }}"
               },
              Tags: [{Key: "configmode", Value: "ansible"},{Key: "prefix", Value: "{{ prefix }}"}]  
           }
    register: lan_connectivity_policy

  - name: "Add {{ name_of_vnic_1 }} to LAN Connectivity Policy - VIC14xx"
    cisco.intersight.intersight_rest_api:
        <<: *api_info_lan_conn
        resource_path: /vnic/EthIfs
        query_params:
           $filter: "Name eq '{{ name_of_vnic_1 }}'"
        api_body: {
             "Name": "{{ name_of_vnic_1 }}",
             "MacAddressType": "POOL",
             "MacPool": "{{ mac_pool_fi_a_details.api_response.Moid }}",
             "Placement": {
                "SwitchId": "A",
                "Id": "{{ vic_slot_id }}",
               #  "PciLink": 0,
                "Uplink": 0
             },
             "Cdn": {
                "Source": "vnic"
             },
             "FailoverEnabled": false,
             "FabricEthNetworkGroupPolicy": [ "{{ management_network_group_policy.api_response.Moid }}" ],
             "FabricEthNetworkControlPolicy": "{{ ethernet_network_control_policy.api_response.Moid }}",
             "EthQosPolicy": "{{ ethernet_qos_policy.api_response.Moid }}",
             "EthAdapterPolicy": "{{ ethernet_adapter_4g_policy.api_response.Moid }}",
             "StaticMacAddress": "",
             "LanConnectivityPolicy": "{{ lan_connectivity_policy.api_response.Moid }}",
             "Order": 0
         }
    when: vic_type == "4G"

  - name: "Add {{ name_of_vnic_2 }} to LAN Connectivity Policy - VIC14xx"
    cisco.intersight.intersight_rest_api:
        <<: *api_info_lan_conn
        resource_path: /vnic/EthIfs
        query_params:
           $filter: "Name eq '{{ name_of_vnic_2 }}'"
        api_body: {
             "Name": "{{ name_of_vnic_2 }}",
             "MacAddressType": "POOL",
             "MacPool": "{{ mac_pool_fi_b_details.api_response.Moid }}",
             "Placement": {
                "SwitchId": "B",
                "Id": "{{ vic_slot_id }}",
               #  "PciLink": 0,
                "Uplink": 0
             },
             "Cdn": {
                "Source": "vnic"
             },
             "FailoverEnabled": false,
             "FabricEthNetworkGroupPolicy": [ "{{ management_network_group_policy.api_response.Moid }}" ],
             "FabricEthNetworkControlPolicy": "{{ ethernet_network_control_policy.api_response.Moid }}",
             "EthQosPolicy": "{{ ethernet_qos_policy.api_response.Moid }}",
             "EthAdapterPolicy": "{{ ethernet_adapter_4g_policy.api_response.Moid }}",
             "StaticMacAddress": "",
             "LanConnectivityPolicy": "{{ lan_connectivity_policy.api_response.Moid }}",
             "Order": 1
         }
    when: vic_type == "4G"

  - name: "Add {{ name_of_vnic_1 }} to LAN Connectivity Policy - VIC15xx"
    cisco.intersight.intersight_rest_api:
        <<: *api_info_lan_conn
        resource_path: /vnic/EthIfs
        query_params:
           $filter: "Name eq '{{ name_of_vnic_1 }}'"
        api_body: {
             "Name": "{{ name_of_vnic_1 }}",
             "MacAddressType": "POOL",
             "MacPool": "{{ mac_pool_fi_a_details.api_response.Moid }}",
             "Placement": {
                "SwitchId": "A",
                "Id": "{{ vic_slot_id }}",
               #  "PciLink": 0,
                "Uplink": 0
             },
             "Cdn": {
                "Source": "vnic"
             },
             "FailoverEnabled": false,
             "FabricEthNetworkGroupPolicy": [ "{{ management_network_group_policy.api_response.Moid }}" ],
             "FabricEthNetworkControlPolicy": "{{ ethernet_network_control_policy.api_response.Moid }}",
             "EthQosPolicy": "{{ ethernet_qos_policy.api_response.Moid }}",
             "EthAdapterPolicy": "{{ ethernet_adapter_5g_policy.api_response.Moid }}",
             "StaticMacAddress": "",
             "LanConnectivityPolicy": "{{ lan_connectivity_policy.api_response.Moid }}",
             "Order": 0
         }
    when: vic_type == "5G"

  - name: "Add {{ name_of_vnic_2 }} to LAN Connectivity Policy - VIC15xx"
    cisco.intersight.intersight_rest_api:
        <<: *api_info_lan_conn
        resource_path: /vnic/EthIfs
        query_params:
           $filter: "Name eq '{{ name_of_vnic_2 }}'"
        api_body: {
             "Name": "{{ name_of_vnic_2 }}",
             "MacAddressType": "POOL",
             "MacPool": "{{ mac_pool_fi_b_details.api_response.Moid }}",
             "Placement": {
                "SwitchId": "B",
                "Id": "{{ vic_slot_id }}",
               #  "PciLink": 0,
                "Uplink": 0
             },
             "Cdn": {
                "Source": "vnic"
             },
             "FailoverEnabled": false,
             "FabricEthNetworkGroupPolicy": [ "{{ management_network_group_policy.api_response.Moid }}" ],
             "FabricEthNetworkControlPolicy": "{{ ethernet_network_control_policy.api_response.Moid }}",
             "EthQosPolicy": "{{ ethernet_qos_policy.api_response.Moid }}",
             "EthAdapterPolicy": "{{ ethernet_adapter_5g_policy.api_response.Moid }}",
             "StaticMacAddress": "",
             "LanConnectivityPolicy": "{{ lan_connectivity_policy.api_response.Moid }}",
             "Order": 1
         }
    when: vic_type == "5G"

  
