---
- name: "Configure PowerPolicy"
  vars:
    api_info: &api_info
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  cisco.intersight.intersight_rest_api:
    <<: *api_info
    resource_path: /power/Policies
    query_params:
       $filter: "Name eq '{{ name_of_power_policy }}'"
    api_body: {
        "Name": "{{ name_of_power_policy }}",
        "Description": "{{ description_of_power_policy }}",
        "PowerProfiling": "{{ power_profiling }}",
        "PowerRestoreState": "{{ power_restore_state }}",
        "PowerPriority": "{{ power_priority }}",
        "RedundancyMode": "{{ redundancy_mode }}",
        "PowerSaveMode": "{{ power_save_mode }}",
        "DynamicRebalancing": "{{ dynamic_rebalancing }}",
        "ExtendedPowerCapacity": "{{ extended_power_capacity }}",
        "AllocatedBudget": "{{ allocated_budget }}",
        "Organization": {
           "Moid": "{{ intersight_org.api_response.Moid }}"
         },
        Tags: [{Key: "configmode", Value: "ansible"},{Key: "prefix", Value: "{{ prefix }}"}]
     }
  register: power_policy
