---
- name: "Get IP Address Pool Details"
  vars:
    api_info: &api_info_ip_pool
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  intersight_rest_api:
    <<: *api_info_ip_pool
    resource_path: /ippool/Pools
    query_params:
      $filter: "Name eq '{{ name_of_ip_pool_for_management_access }}'"

  register:  management_ip_pool_details

- name: "Get MAC Address Details for FI-A"
  vars:
    api_info: &api_info_mac_a_pool
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  intersight_rest_api:
    <<: *api_info_mac_a_pool
    resource_path: /macpool/Pools
    query_params:
      $filter: "Name eq '{{ name_of_mac_pool_on_fi_a }}'"

  register:  mac_pool_fi_a_details

- name: "Get MAC Address Details for FI-B"
  vars:
    api_info: &api_info_mac_b_pool
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  intersight_rest_api:
    <<: *api_info_mac_b_pool
    resource_path: /macpool/Pools
    query_params:
      $filter: "Name eq '{{ name_of_mac_pool_on_fi_b }}'"

  register:  mac_pool_fi_b_details

